library(cowplot)
library(ggplot2)
library(plotly)
library(flexdashboard)
library(MASS)
library(car)
library(e1071)
library(caret)
library(ggplot2)
library(cowplot)
library(caTools)
library(readr)
# devtools::install_github("rstudio/flexdashboard")